name: Run Laravel Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, bcmath, xml, ctype, fileinfo
          tools: composer

      - name: Copy .env
        run: cp .env.example .env

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Set APP_KEY
        run: php artisan key:generate --force
        env:
          APP_KEY: ${{ secrets.APP_KEY }}

      - name: Run tests
        run: php artisan test
      - run: vendor/bin/phpstan analyse
      - run: vendor/bin/pest --coverage
