on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
      - run: composer install --prefer-dist --no-progress
      - run: vendor/bin/phpstan analyse
      - run: vendor/bin/pest --coverage
